defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm run test


  analyse:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm i
      - run: npm audit

workflows:
  CI_workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyse:
          requires: 
            - test