defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command : npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command : npm run test


  analyse:
    <<: *defaults
    steps:
      - checkout
      - run:
          command : npm audit

workflows:
  jobs:
    - build
    - test:
        requires: build
    - analyse:
        requires: test